version: '3'
services:
  redis:
    image: redis:latest
    restart: always
  web:
    build: ./app
    command: ruby app.rb -o 0.0.0.0
    ports:
      - "127.0.0.1:9001:4567"
    links:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

